### ISSUE TITLE
What is difference between classic algebras/coalgebras

### ISSUE THREAD

**Issue by xgrommx** [mbuszka/purescript-record-recursion-schemes#3]
Hello @mbuszka I have question about your implementation. What is difference between classic f-algebras? for example
```hs
type Algebra f a = f a -> a
type Coalgebra f a -> a -> f a
```
also where Mu/Nu/Fix? and classic catamorphism

Thanks!

**Comment by mbuszka** [comment]
Hello @xgrommx. To be honest this repository is just misleadingly named, because I was inspired by classic recursion schemes and drew the names and concepts from the paper. What i implemented here is just a `foldr`, but both on types and values. So the `class Cata` should probably be called `class Fold` and instead of `class Algebra` i should have called it `class Step`.

**Comment by xgrommx** [comment]
@mbuszka okay!) thanks
